### ISSUE TITLE
Bitbucket support

### ISSUE THREAD

**Issue by smaslenko** [staff0rd/github-follow-extension#1]
First of all, thank you for your great work!
But this plugin could be doubly useful by including support for Bitbucket as well. Is it possible to implement?

**Comment by staff0rd** [comment]
I don't think i've ever browsed source on bitbucket - I mainly use it as a private backup for projects that are not active.  Can you supply a link to a source file on bitbucket that's been moved?

**Comment by staff0rd** [comment]
[GitHub now implements](https://github.blog/changelog/2022-06-06-view-commit-history-across-file-renames-and-moves/) this extension's key feature. I will archive this project.
