### ISSUE TITLE
The "follow" button is not shown if the commit renamed more than 300 files

### ISSUE THREAD

**Issue by gusehr** [staff0rd/github-follow-extension#3]
Hi there!

First of all, thank you for the extension!! It is very useful :+1: 

I got an issue when the "rename commit" has more than 300 files. The "follow" button is not show.
I think that it is an GitHub API limitation.

Do we have some alternative?
What do you think?

Thanks in advance.

**Comment by staff0rd** [comment]
Heya - have you got a commit url I can use to check this out?

**Comment by gusehr** [comment]
Hey @staff0rd 

I have this situation in a private repo.
I will prepare this on a mocked public repo.

I will send the link ASAP.

**Comment by gusehr** [comment]
Hi there.

I've created an test repository for this issue:
https://github.com/gusehr/github-follow-extension-test/commits/master
The repository contains 500 renamed files.

The "follow" button appears correctly at this URL:
https://github.com/gusehr/github-follow-extension-test/commits/master/renamed/file0300.test

But it is not shown at this URL on:
https://github.com/gusehr/github-follow-extension-test/commits/master/renamed/file0301.test

What do you think?

**Comment by staff0rd** [comment]
Are you certain that file was moved?  The response from the github API includes the following for those two files.  Notice that the first one has a status of `renamed` and includes a `previous_filename`, and the second does not, which is why github-follow-extension is not displaying the button...

```
    {
      "sha": "daffdc82343e6c9382fd1733e9ac0586ce70d11d",
      "filename": "renamed/file0300.test",
      "status": "renamed",
      "additions": 0,
      "deletions": 0,
      "changes": 0,
      "blob_url": "https://github.com/gusehr/github-follow-extension-test/blob/53acc8d827108433e28818f26b156a2d9b95ec6c/renamed/file0300.test",
      "raw_url": "https://github.com/gusehr/github-follow-extension-test/raw/53acc8d827108433e28818f26b156a2d9b95ec6c/renamed/file0300.test",
      "contents_url": "https://api.github.com/repos/gusehr/github-follow-extension-test/contents/renamed/file0300.test?ref=53acc8d827108433e28818f26b156a2d9b95ec6c",
      "previous_filename": "original/file0300.test"
    },
    {
      "sha": null,
      "filename": "renamed/file0301.test",
      "status": "changed",
      "additions": 0,
      "deletions": 0,
      "changes": 0,
      "blob_url": "https://github.com/gusehr/github-follow-extension-test/blob/53acc8d827108433e28818f26b156a2d9b95ec6c/renamed/file0301.test",
      "raw_url": "https://github.com/gusehr/github-follow-extension-test/raw/53acc8d827108433e28818f26b156a2d9b95ec6c/renamed/file0301.test",
      "contents_url": "https://api.github.com/repos/gusehr/github-follow-extension-test/contents/renamed/file0301.test?ref=53acc8d827108433e28818f26b156a2d9b95ec6c"
    }
```

**Comment by gusehr** [comment]
Hi @staff0rd!

I'm sure that the file was renamed.
I created the folder "original" with 500 files, then renamed the folder to "renamed".

If I use the -- follow option on git terminal I see this output:

```
gustavo@gustavo-X550LA:/prj/github-follow-extension-test$ git log --follow renamed/file0301.test
commit 53acc8d827108433e28818f26b156a2d9b95ec6c
Author: Gustavo Ehrhardt <gus.ehr@gmail.com>
Date:   Fri Oct 21 09:22:14 2016 -0200

    renamed folder

commit 1eb8d7aedd91453a9ddb419fc3de81d63eac6e4c
Author: Gustavo Ehrhardt <gus.ehr@gmail.com>
Date:   Fri Oct 21 09:21:23 2016 -0200

    my first change

commit 61a0ee760e6e2f9884be1d9dc2b210e9423f43d0
Author: Gustavo Ehrhardt <gus.ehr@gmail.com>
Date:   Fri Oct 21 09:17:53 2016 -0200

    original files created
```

**Comment by staff0rd** [comment]
git spits out some weird shit in the diff for that last commit;

```
$ git --no-pager diff 53acc8d827108433e28818f26b156a2d9b95ec6c 1eb8d7aedd91453a9ddb419fc3de81d63eac6e 4c -M | grep file0301
diff --git a/renamed/file0301.test b/original/file0200.test
rename from renamed/file0301.test
diff --git a/renamed/file0200.test b/original/file0301.test
rename to original/file0301.test
```

Additionally, the commit notes 700 changes, but there's only 500 files in that directory.  I wonder if some re-naming collision has occurred here, ie; renames occurring twice against the same file?

**Comment by gusehr** [comment]
Hi there.

I think that de similarity of all files is the cause of the miss output.
Please, look the output file of this command.

```
git --no-pager diff 53acc8d827108433e28818f26b156a2d9b95ec6c 1eb8d7aedd91453a9ddb419fc3de81d63eac6e > diff.out
```

**Comment by gusehr** [comment]
Hi @staff0rd !

Have you had any conclusions about this?
Thanks in advance.

**Comment by staff0rd** [comment]
Heya - sorry lack of time at the moment for this.  I'd recommend checking out the API docs, and/or firing some API requests yourself at the github API to determine whether the results of a commit can be paged.  The command github-follow-extension is calling is this;

```
https://api.github.com/repos/gusehr/github-follow-extension-test/commits/53acc8d827108433e28818f26b156a2d9b95ec6c#diff-bd3ca5d803e1ff138c374c9bc95492bf
```

The end of the result is what was posted [here](https://github.com/staff0rd/github-follow-extension/issues/3#issuecomment-255576800).

If the API can't page and there's no good reason for `renamed/file0301.test` returning as `changed` rather than `renamed` then I guess it's a limitation (and possibly bug) of the API.

**Comment by gusehr** [comment]
Hi there!
No problem about the late.

I see. The "file 301" is not the only problem, but the files from "301 to 500" too.
I think this is a GitHub API issue which doesn't support pagination for the files lists.

I have found an "unofficial" GitHub issues list. The list mention this problem: https://github.com/isaacs/github/issues/587

What do you think about the github-follow-extension issue?
Add a known issues section in the main page, and then close this one?
Keep opened util GitHub adds the pagination feature?

See ya.

**Comment by staff0rd** [comment]
Yah - that issue seems specific to the UI rather than the API however.  

We'll just leave this issue open until a workaround/fix can happen.

**Comment by staff0rd** [comment]
[GitHub now implements](https://github.blog/changelog/2022-06-06-view-commit-history-across-file-renames-and-moves/) this extension's key feature. I will archive this project.
