### ISSUE TITLE
GitHub enterprise support

### ISSUE THREAD

**Issue by laurencee** [staff0rd/github-follow-extension#4]
GitHub enterprise is just an on premise version of GitHub with some extra authentication methods.

Can this extension be updated so it can work with an on premise github as well?
I'm guessing the matches here need to change:
https://github.com/staff0rd/github-follow-extension/blob/master/app/manifest.json#L24

For example our setup is github.company.com so a github.*com match would probably be fine.

**Comment by staff0rd** [comment]
Hiya - if you make a PR for this i'll merge it in.  I don't have access to any enterprise instances so I can't test it however.

**Comment by laurencee** [comment]
Just tested on one of my larger projects and xunit tests in general just take way longer to run in resharpers test runner than under vstest (test explorer in VS).

**Comment by staff0rd** [comment]
[GitHub now implements](https://github.blog/changelog/2022-06-06-view-commit-history-across-file-renames-and-moves/) this extension's key feature. I will archive this project.
