### ISSUE TITLE
Firefox add-on

### ISSUE THREAD

**Issue by jtojnar** [staff0rd/github-follow-extension#5]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

**Comment by pradyunsg** [comment]
Ping?

**Comment by staff0rd** [comment]
I don't use firefox, but you guys are welcome to send a pull request or fork this.

**Comment by staff0rd** [comment]
[GitHub now implements](https://github.blog/changelog/2022-06-06-view-commit-history-across-file-renames-and-moves/) this extension's key feature. I will archive this project.
