### ISSUE TITLE
`Follow` button not shown due to failed to get the SHA

### ISSUE THREAD

**Issue by vincentbel** [staff0rd/github-follow-extension#7]
![image](https://user-images.githubusercontent.com/6076919/39240525-9451e80c-48b6-11e8-8e1c-179c99e752d4.png)

It seems there are no `data-clipboard-text` attribute on `<clipboard-copy>` now, and should use the `value` attribute instead.

https://github.com/staff0rd/github-follow-extension/blob/f34d0755d2ffce59b31a0751ec7ebf795c82c290/app/scripts/history.js#L29

to:

```js
$('clipboard-copy').last().attr('value'); 
```

**Comment by staff0rd** [comment]
Fixed, thanks for the report @VincentBel
