### ISSUE TITLE
Don't manage to use the extension

### ISSUE THREAD

**Issue by laurentgaertner** [staff0rd/github-follow-extension#9]
I've installed the extension.
In the history view I can't se the "follow" button

**Comment by staff0rd** [comment]
Hi @laurentgaertner, looks to be working to me;

Check this page; https://github.com/staff0rd/git-follow-test/commits/dev/file1

I just installed the extension and I see this;

![image](https://user-images.githubusercontent.com/6289998/52203145-8ca78280-28c4-11e9-8ba7-43cf87426829.png)

Let me know if you're still having trouble.
